repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: name-tests-test
        args: [--pytest-test-first]
        exclude: tests/.*fixtures_.*\.py
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        stages: [pre-push]
        types: [python]
        entry: python -m poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
      - id: mypy-check
        name: mypy-check
        stages: [pre-push]
        types: [python]
        entry: python -m poetry run mypy .
        language: system
        pass_filenames: false
        always_run: true
