# Email address used to log in to the IMAP server.
user_email: "your_username@example.com"

# IMAP server host for your email provider.
imap_host: "imap.virginmedia.com"

# Service name used by keyring for password retrieval.
keyring_service: "virgin-imap"

# Mapping of IMAP folder names to short local labels.
# Make sure the IMAP keys exactly match your actual mailbox folder names.
folder_map:
  INBOX: inbox     # Standard inbox folder
  Spam: spam       # Spam or junk mail folder
# Trash: trash     # Add more if needed
